# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'all_albums_warning_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AllAlbumsWarningDialog(object):
    def setupUi(self, AllAlbumsWarningDialog):
        AllAlbumsWarningDialog.setObjectName("AllAlbumsWarningDialog")
        AllAlbumsWarningDialog.resize(480, 304)
        AllAlbumsWarningDialog.setMinimumSize(QtCore.QSize(480, 240))
        self.verticalLayout = QtWidgets.QVBoxLayout(AllAlbumsWarningDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerLayout = QtWidgets.QHBoxLayout()
        self.headerLayout.setObjectName("headerLayout")
        self.iconLabel = QtWidgets.QLabel(AllAlbumsWarningDialog)
        self.iconLabel.setMinimumSize(QtCore.QSize(48, 48))
        self.iconLabel.setMaximumSize(QtCore.QSize(48, 48))
        self.iconLabel.setText("")
        self.iconLabel.setPixmap(QtGui.QPixmap(":/icons/dialog-warning.png"))
        self.iconLabel.setScaledContents(False)
        self.iconLabel.setObjectName("iconLabel")
        self.headerLayout.addWidget(self.iconLabel)
        self.headerLabel = QtWidgets.QLabel(AllAlbumsWarningDialog)
        self.headerLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.headerLabel.setWordWrap(False)
        self.headerLabel.setObjectName("headerLabel")
        self.headerLayout.addWidget(self.headerLabel, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addLayout(self.headerLayout)
        self.browser = QtWidgets.QTextBrowser(AllAlbumsWarningDialog)
        self.browser.setReadOnly(True)
        self.browser.setOpenExternalLinks(False)
        self.browser.setObjectName("browser")
        self.verticalLayout.addWidget(self.browser)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem)
        self.closeButton = QtWidgets.QPushButton(AllAlbumsWarningDialog)
        self.closeButton.setDefault(False)
        self.closeButton.setObjectName("closeButton")
        self.buttonLayout.addWidget(self.closeButton)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(AllAlbumsWarningDialog)
        QtCore.QMetaObject.connectSlotsByName(AllAlbumsWarningDialog)

    def retranslateUi(self, AllAlbumsWarningDialog):
        _translate = QtCore.QCoreApplication.translate
        AllAlbumsWarningDialog.setWindowTitle(_translate("AllAlbumsWarningDialog", "Warnings: different embedded covers"))
        self.headerLabel.setText(_translate("AllAlbumsWarningDialog", "Albums with differing embedded covers"))
        self.closeButton.setText(_translate("AllAlbumsWarningDialog", "Close"))
